---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/countries":
    post:
      summary: Creates a country
      tags:
      - Countries
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: country
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '201':
          description: country created
        '422':
          description: invalid request
  "/countries/{id}":
    get:
      summary: Retrieves a country
      tags:
      - Countries
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: name found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required:
            - id
            - name
            - status
        '404':
          description: country not found
